<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android</TargetFrameworks>
		<TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('linux'))">$(TargetFrameworks);net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>

		<MauiXamlInflator>SourceGen</MauiXamlInflator>

		<OutputType>Exe</OutputType>
		<RootNamespace>TaskTracker.Maui</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- ================= DISPLAY ================= -->
		<ApplicationTitle>TaskTracker</ApplicationTitle>
		<AssemblyName>TaskTracker</AssemblyName>

		<!-- ================= APP ID ================= -->
		<ApplicationId>com.companyname.tasktracker.maui</ApplicationId>
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- ================= WINDOWS ================= -->
		<WindowsPackageType>None</WindowsPackageType>

		<ApplicationIcon Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">Resources\AppIcon\tasktracker.ico</ApplicationIcon>
		<PublishSingleFile Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">true</PublishSingleFile>
		<SelfContained Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">true</SelfContained>
		<PublishTrimmed Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">false</PublishTrimmed>

		<!-- Убираем языковые папки кроме английского -->
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>

		<!-- Убираем .pdb в релизе -->
		<DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>

		<!-- ================= PLATFORM VERSIONS ================= -->
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
	</PropertyGroup>

	<ItemGroup>
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		<MauiFont Include="Resources\Fonts\*" />
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
		<AndroidJavaSource Remove="Features\Settings\**" />
		<AndroidLibrary Remove="Features\Settings\**" />
		<AndroidNativeLibrary Remove="Features\Settings\**" />
		<Compile Remove="Features\Settings\**" />
		<EmbeddedResource Remove="Features\Settings\**" />
		<JavaSourceJar Remove="Features\Settings\**" />
		<None Remove="Features\Settings\**" />
		<ProguardConfiguration Remove="Features\Settings\**" />
		<TransformFile Remove="Features\Settings\**" />
		<Compile Include="Features\Settings\SettingsPage.xaml.cs" />
		<EmbeddedResource Include="appsettings.json" LogicalName="TaskTracker.Maui.appsettings.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="CommunityToolkit.Maui" Version="14.2.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.8" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.71" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
	</ItemGroup>

	<ItemGroup>
		<MauiXaml Update="Features\Auth\Views\LoginPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Features\Projects\Views\CreateProjectPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Features\Projects\Views\ProjectDetailsPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Features\Projects\Views\EditProjectPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Features\Projects\Views\ProjectsPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Features\Users\Popups\UserPickerPopup.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Features\Users\Views\CreateUserPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Features\Users\Views\EditUserPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Features\Users\Views\UserDetailsPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Features\Users\Views\UsersPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Features\WorkItems\Views\CreateWorkItemPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Features\Documents\Popups\DocumentsPopup.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Features\WorkItems\Popups\EditWorkItemPopup.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TaskTracker.Application\TaskTracker.Application.csproj" />
	</ItemGroup>

</Project>